Add Aspect Ratio component
Amsterdam/design-system pull request #573
Opened 2023-09-28 09:37 UTC by alimpens

2023-09-29 13:38 UTC, VincentSmedinga requested changes

2023-09-29 14:25 UTC, alimpens commented on packages/css/src/aspect-ratio/README.md
> +# Aspect ratio
Good idea, I'll change it for all docs

2023-09-29 14:25 UTC, alimpens commented on packages/css/src/aspect-ratio/README.md
> +Gebruik Aspect Ratio (in het Nederlands: beeldverhouding) om de breedte van een element te koppelen aan de hoogte. Hoe smaller het element, hoe minder hoog.
Maybe something like this?
```suggestion
Aspect Ratio (in het Nederlands: beeldverhouding) koppelt de hoogte van een element aan de breedte.
```

2023-09-29 14:25 UTC, alimpens commented on packages/css/src/aspect-ratio/README.md
> +Dit component staat een vaste set verhoudingen (breedte:hoogte) toe, zodat het element dat het bevat een consistent formaat heeft:
Hm, the 'staande en liggende modus' part doesn't really make this part clearer, in my opinion. Maybe something like:

```suggestion
Om de vormgeving consistent te houden gebruiken we een vaste set verhoudingen (breedte:hoogte):
```

2023-09-29 14:25 UTC, alimpens commented on packages/css/src/aspect-ratio/README.md
> +- Niet gebruiken met elementen met een statische grootte (hoogte en/of breedte), dan klopt de beeldverhouding niet.
I agree, that's not very clear. I'm basically trying to say: the contents of AspectRatio should have width: 100%. Any idea on how to simply convey that?

2023-09-29 14:25 UTC, alimpens commented on storybook/storybook-react/src/AspectRatio/AspectRatio.stories.tsx
> +const textStyle = {
I kinda like to make it very explicit what the keywords ('extra-tall', 'tall' etc.) mean in terms of aspect ratio, which is why I chose this approach. Do you think it's not necessary to make it explicit here? Or do you prefer to make it explicit in a different way?

2023-09-29 14:25 UTC, alimpens commented on storybook/storybook-react/src/AspectRatio/AspectRatio.stories.tsx
> +export const Default: Story = {
What 'Default' shows is dependent on the controls. If you set the controls to 'extra-wide', that's what you get. It's weird imo to show that under the heading 'Square'

2023-10-03 09:54 UTC, VincentSmedinga commented on packages/css/src/aspect-ratio/README.md
> +- Niet gebruiken met elementen met een statische grootte (hoogte en/of breedte), dan klopt de beeldverhouding niet.
Let’s make it easy for ourselves and remove it for now.

```suggestion```

We’re already working on Card, and on Image in one or two weeks, and a prototype of our website in the browser. We’ll find out soon enough how to use and document this.

2023-10-03 10:16 UTC, VincentSmedinga commented on storybook/storybook-react/src/AspectRatio/AspectRatio.stories.tsx
> +const textStyle = {
I think the list in the documentation is very clear.

2023-10-03 10:18 UTC, VincentSmedinga commented on storybook/storybook-react/src/AspectRatio/AspectRatio.stories.tsx
> +function getStoryConfig(ratio: string | undefined) {
You may have missed this suggestion?

2023-10-04 07:38 UTC, alimpens commented on storybook/storybook-react/src/AspectRatio/AspectRatio.stories.tsx
> +const textStyle = {
I removed the overlay, and turned the list in the docs to a table

2023-10-04 07:38 UTC, alimpens commented on storybook/storybook-react/src/AspectRatio/AspectRatio.stories.tsx
> +function getStoryConfig(ratio: string | undefined) {
Ah, you're right. I don't quite understand the suggestion, this is a function that returns an object? Why not just define an object straight away?

```
const storyConfig = {
  "extra-tall: {},
  "tall": {},
  ...
}
```

2023-10-04 11:42 UTC, VincentSmedinga requested changes

2023-10-04 11:42 UTC, VincentSmedinga commented on storybook/storybook-react/src/AspectRatio/AspectRatio.stories.tsx
> +function getStoryConfig(ratio: string | undefined) {
Sure!

2023-10-04 11:42 UTC, VincentSmedinga commented on storybook/storybook-react/src/AspectRatio/AspectRatio.docs.mdx
> +## Extra Tall
Sorry, can you do the keywords table as well? And the options for `ratio` in the args table?

2023-10-04 12:04 UTC, VincentSmedinga approved these changes

2023-10-04 12:04 UTC, merged